### ISSUE TITLE
tag technology support

### ISSUE THREAD

**Issue by shrikantbadwaik** [tawaasalage/SimpleNFC#1]
I have a question related to this. Does this supports reading all tech technologies other than NDEF mentioned in Table 1 & 2 on Official Android Documentation [https://developer.android.com/guide/topics/connectivity/nfc/advanced-nfc.html](here).

Reason why I'm asking this is because in below code you have specifically null checked on ndef.
`public String nfcRead(Tag t) {
        try {
            Tag tag = t;
            Ndef ndef = Ndef.get(tag);
            if (ndef == null) {
                return null;
            }
            NdefMessage ndefMessage = ndef.getCachedNdefMessage();
            NdefRecord[] records = ndefMessage.getRecords();
            for (NdefRecord ndefRecord : records)
            {
                if (ndefRecord.getTnf() == NdefRecord.TNF_WELL_KNOWN && Arrays.equals(ndefRecord.getType(), NdefRecord.RTD_TEXT))
                {
                    try {return readText(ndefRecord);} catch (UnsupportedEncodingException e) {}
                }
            }
        }
        catch (Exception e)
        {
            return null;
        }
        return null;
    }`

**Comment by tawaasalage** [comment]
Yes I have tested this with multiple NFC cards (from more than 20 plus vendors) the reason why I have added that exception is some times when I swipe the same card it returns null pointer exception (May be due to phone NFC communication error) this happens very rarely so for safety I have added that exception.

**Comment by shrikantbadwaik** [comment]
@tawaasalage but in that method you are doing operations on NDEFMessage only so how come you are able to read message based on other tech such as NfcA, NfcB, etc.?

**Comment by tawaasalage** [comment]
Sorry  @ShrikantBadwaik-007 I haven't tried NfcA, NfcB type NFC cards but as you can see from below code can get it to work.
NfcA nfca=NfcA.get(tag);
          nfca.connect();
            Short s = nfca.getSak();
            byte[] a = nfca.getAtqa();
            String atqa = new String(a, Charset.forName("US-ASCII"));

**Comment by shrikantbadwaik** [comment]
ok got it, thanks
